version: '3'

services:
  web:

    image: webdevops/php-apache:latest

    ports:
      - 80

    environment:
      WEB_DOCUMENT_ROOT: /app/public

      VIRTUAL_HOST: projectname.dev.test

      HTTPS_METHOD: redirect

    volumes:
      - ./:/app

networks:
  default:
    external:
      name: dash    